// src/lib/mock-data.ts
// Dataset de fallback para quando as APIs externas (PNCP, TransfereGov) estão indisponíveis.

import type { Oportunidade } from './types'

export interface MockVencedor {
  cnpj: string
  nome: string
  vitorias: number
  valorTotal: number
}

export interface MockPreco {
  id: string
  codigoItem: string
  descricaoItem: string
  unidadeMedida: string
  valorUnitario: number
  quantidade: number
  valorTotal: number
  dataResultado: string
  nomeOrgao: string
  siglaUf: string
  municipio?: string
  cnpjFornecedor: string
  razaoSocialFornecedor: string
  numeroDocumento?: string
  origem: 'contrato' | 'ata'
}

const NOW = new Date()
function daysAgo(n: number) {
  const d = new Date(NOW)
  d.setDate(d.getDate() - n)
  return d.toISOString()
}
function daysFromNow(n: number) {
  const d = new Date(NOW)
  d.setDate(d.getDate() + n)
  return d.toISOString()
}

export const MOCK_OPORTUNIDADES: Oportunidade[] = [
  // ── URGENTES (prazo ≤ 7d) ────────────────────────────────────────────────
  {
    id: 'mock-001',
    municipio: 'São Paulo',
    uf: 'SP',
    regiao: 'sudeste',
    hospital: 'Hospital das Clínicas FMUSP',
    categoria: 'imagem',
    descricao: 'Aquisição de tomógrafo computadorizado de 128 canais com mesa flutuante',
    score: 97,
    subScores: { convenio: 95, historico: 90, orgao: 98, competicao: 85 },
    valorEstimado: 3_800_000,
    janelaEmDias: 4,
    urgencia: 'urgente',
    status: 'quente',
    probabilidadeEdital: 1.0,
    concorrentes: [],
    indiceConcorrencia: 'alto',
    acaoRecomendada: 'Edital aberto — encerra em 4d. Preparar proposta AGORA.',
    licitacaoRelacionada: {
      id: 'PNCP-SP-2026-001',
      numeroControlePNCP: '23077.001/2026-001',
      orgaoEntidade: { cnpj: '63025530000104', razaoSocial: 'Hospital das Clínicas FMUSP', municipio: 'São Paulo', uf: 'SP' },
      modalidadeNome: 'Pregão Eletrônico',
      objetoCompra: 'Aquisição de tomógrafo computadorizado de 128 canais com mesa flutuante e software de pós-processamento',
      valorTotalEstimado: 3_800_000,
      dataPublicacaoPncp: daysAgo(10),
      dataEncerramentoProposta: daysFromNow(4),
      situacaoCompraId: 1,
      situacaoCompraNome: 'Publicada',
      linkSistemaOrigem: 'https://www.comprasnet.gov.br',
    },
    createdAt: daysAgo(10),
    updatedAt: daysAgo(1),
  },
  {
    id: 'mock-002',
    municipio: 'Rio de Janeiro',
    uf: 'RJ',
    regiao: 'sudeste',
    hospital: 'Hospital Federal de Ipanema',
    categoria: 'uti',
    descricao: 'Contratação de ventiladores pulmonares para UTI adulto e neonatal (40 unidades)',
    score: 95,
    subScores: { convenio: 90, historico: 85, orgao: 92, competicao: 78 },
    valorEstimado: 2_100_000,
    janelaEmDias: 6,
    urgencia: 'urgente',
    status: 'quente',
    probabilidadeEdital: 1.0,
    concorrentes: [],
    indiceConcorrencia: 'medio',
    acaoRecomendada: 'Edital aberto — encerra em 6d. Preparar proposta AGORA.',
    licitacaoRelacionada: {
      id: 'PNCP-RJ-2026-001',
      numeroControlePNCP: '00394.001/2026-001',
      orgaoEntidade: { cnpj: '03740903000104', razaoSocial: 'Hospital Federal de Ipanema', municipio: 'Rio de Janeiro', uf: 'RJ' },
      modalidadeNome: 'Pregão Eletrônico',
      objetoCompra: 'Contratação de ventiladores pulmonares para UTI adulto e neonatal',
      valorTotalEstimado: 2_100_000,
      dataPublicacaoPncp: daysAgo(8),
      dataEncerramentoProposta: daysFromNow(6),
      situacaoCompraId: 1,
      situacaoCompraNome: 'Publicada',
      linkSistemaOrigem: 'https://www.comprasnet.gov.br',
    },
    createdAt: daysAgo(8),
    updatedAt: daysAgo(1),
  },
  {
    id: 'mock-003',
    municipio: 'Belo Horizonte',
    uf: 'MG',
    regiao: 'sudeste',
    hospital: 'Santa Casa de Misericórdia de BH',
    categoria: 'laboratorio',
    descricao: 'Aquisição de analisador hematológico de 6 parâmetros com reagentes por 12 meses',
    score: 93,
    subScores: { convenio: 88, historico: 80, orgao: 90, competicao: 70 },
    valorEstimado: 980_000,
    janelaEmDias: 3,
    urgencia: 'urgente',
    status: 'quente',
    probabilidadeEdital: 1.0,
    concorrentes: [],
    indiceConcorrencia: 'baixo',
    acaoRecomendada: 'Edital aberto — encerra em 3d. Preparar proposta AGORA.',
    licitacaoRelacionada: {
      id: 'PNCP-MG-2026-001',
      numeroControlePNCP: '17895.001/2026-001',
      orgaoEntidade: { cnpj: '17895745000168', razaoSocial: 'Santa Casa de Misericórdia de BH', municipio: 'Belo Horizonte', uf: 'MG' },
      modalidadeNome: 'Pregão Eletrônico',
      objetoCompra: 'Aquisição de analisador hematológico de 6 parâmetros com fornecimento de reagentes',
      valorTotalEstimado: 980_000,
      dataPublicacaoPncp: daysAgo(12),
      dataEncerramentoProposta: daysFromNow(3),
      situacaoCompraId: 1,
      situacaoCompraNome: 'Publicada',
      linkSistemaOrigem: 'https://www.comprasnet.gov.br',
    },
    createdAt: daysAgo(12),
    updatedAt: daysAgo(2),
  },
  // ── ALTA PRIORIDADE (prazo 8–30d) ─────────────────────────────────────────
  {
    id: 'mock-004',
    municipio: 'Campinas',
    uf: 'SP',
    regiao: 'sudeste',
    hospital: 'Hospital Municipal Dr. Mário Gatti',
    categoria: 'imagem',
    descricao: 'Aquisição de aparelho de ressonância magnética 1.5 Tesla com sistema de refrigeração',
    score: 91,
    subScores: { convenio: 85, historico: 88, orgao: 92, competicao: 80 },
    valorEstimado: 5_500_000,
    janelaEmDias: 14,
    urgencia: 'alta',
    status: 'quente',
    probabilidadeEdital: 1.0,
    concorrentes: [],
    indiceConcorrencia: 'alto',
    acaoRecomendada: 'Edital aberto — 14 dias restantes. Iniciar proposta.',
    licitacaoRelacionada: {
      id: 'PNCP-SP-2026-002',
      numeroControlePNCP: '12345.001/2026-002',
      orgaoEntidade: { cnpj: '45685425000111', razaoSocial: 'Hospital Municipal Dr. Mário Gatti', municipio: 'Campinas', uf: 'SP' },
      modalidadeNome: 'Concorrência',
      objetoCompra: 'Aquisição de aparelho de ressonância magnética 1.5 Tesla com sistema de refrigeração e software',
      valorTotalEstimado: 5_500_000,
      dataPublicacaoPncp: daysAgo(16),
      dataEncerramentoProposta: daysFromNow(14),
      situacaoCompraId: 1,
      situacaoCompraNome: 'Publicada',
      linkSistemaOrigem: 'https://www.comprasnet.gov.br',
    },
    createdAt: daysAgo(16),
    updatedAt: daysAgo(1),
  },
  {
    id: 'mock-005',
    municipio: 'Salvador',
    uf: 'BA',
    regiao: 'nordeste',
    hospital: 'Hospital Geral Roberto Santos',
    categoria: 'cirurgia',
    descricao: 'Aquisição de mesas cirúrgicas elétricas multiposicionais (10 unidades)',
    score: 89,
    subScores: { convenio: 82, historico: 78, orgao: 86, competicao: 72 },
    valorEstimado: 1_850_000,
    janelaEmDias: 21,
    urgencia: 'alta',
    status: 'quente',
    probabilidadeEdital: 1.0,
    concorrentes: [],
    indiceConcorrencia: 'medio',
    acaoRecomendada: 'Edital aberto — 21 dias restantes. Iniciar proposta.',
    licitacaoRelacionada: {
      id: 'PNCP-BA-2026-001',
      numeroControlePNCP: '13307.001/2026-001',
      orgaoEntidade: { cnpj: '13307682000101', razaoSocial: 'Hospital Geral Roberto Santos', municipio: 'Salvador', uf: 'BA' },
      modalidadeNome: 'Pregão Eletrônico',
      objetoCompra: 'Aquisição de mesas cirúrgicas elétricas multiposicionais para centro cirúrgico',
      valorTotalEstimado: 1_850_000,
      dataPublicacaoPncp: daysAgo(9),
      dataEncerramentoProposta: daysFromNow(21),
      situacaoCompraId: 1,
      situacaoCompraNome: 'Publicada',
      linkSistemaOrigem: 'https://www.comprasnet.gov.br',
    },
    createdAt: daysAgo(9),
    updatedAt: daysAgo(2),
  },
  {
    id: 'mock-006',
    municipio: 'Porto Alegre',
    uf: 'RS',
    regiao: 'sul',
    hospital: 'Hospital de Clínicas de Porto Alegre',
    categoria: 'oncologia',
    descricao: 'Contratação de acelerador linear para radioterapia com sistema IGRT',
    score: 92,
    subScores: { convenio: 90, historico: 88, orgao: 95, competicao: 65 },
    valorEstimado: 8_200_000,
    janelaEmDias: 28,
    urgencia: 'alta',
    status: 'quente',
    probabilidadeEdital: 1.0,
    concorrentes: [],
    indiceConcorrencia: 'baixo',
    acaoRecomendada: 'Edital aberto — 28 dias restantes. Iniciar proposta técnica.',
    licitacaoRelacionada: {
      id: 'PNCP-RS-2026-001',
      numeroControlePNCP: '92600.001/2026-001',
      orgaoEntidade: { cnpj: '92600003000172', razaoSocial: 'Hospital de Clínicas de Porto Alegre', municipio: 'Porto Alegre', uf: 'RS' },
      modalidadeNome: 'Concorrência',
      objetoCompra: 'Contratação de acelerador linear para radioterapia com sistema de guia por imagem (IGRT)',
      valorTotalEstimado: 8_200_000,
      dataPublicacaoPncp: daysAgo(2),
      dataEncerramentoProposta: daysFromNow(28),
      situacaoCompraId: 1,
      situacaoCompraNome: 'Publicada',
      linkSistemaOrigem: 'https://www.comprasnet.gov.br',
    },
    createdAt: daysAgo(2),
    updatedAt: daysAgo(1),
  },
  {
    id: 'mock-007',
    municipio: 'Brasília',
    uf: 'DF',
    regiao: 'centro-oeste',
    hospital: 'Hospital Regional de Taguatinga',
    categoria: 'uti',
    descricao: 'Aquisição de monitores multiparamétricos com desfibrilador integrado (20 unidades)',
    score: 88,
    subScores: { convenio: 84, historico: 80, orgao: 88, competicao: 75 },
    valorEstimado: 1_460_000,
    janelaEmDias: 18,
    urgencia: 'alta',
    status: 'quente',
    probabilidadeEdital: 1.0,
    concorrentes: [],
    indiceConcorrencia: 'medio',
    acaoRecomendada: 'Edital aberto — 18 dias restantes. Iniciar proposta.',
    licitacaoRelacionada: {
      id: 'PNCP-DF-2026-001',
      numeroControlePNCP: '00414.001/2026-001',
      orgaoEntidade: { cnpj: '00414607000174', razaoSocial: 'Hospital Regional de Taguatinga', municipio: 'Brasília', uf: 'DF' },
      modalidadeNome: 'Pregão Eletrônico',
      objetoCompra: 'Aquisição de monitores multiparamétricos com desfibrilador integrado para UTI',
      valorTotalEstimado: 1_460_000,
      dataPublicacaoPncp: daysAgo(12),
      dataEncerramentoProposta: daysFromNow(18),
      situacaoCompraId: 1,
      situacaoCompraNome: 'Publicada',
      linkSistemaOrigem: 'https://www.comprasnet.gov.br',
    },
    createdAt: daysAgo(12),
    updatedAt: daysAgo(1),
  },
  // ── ABERTOS (prazo > 30d) ─────────────────────────────────────────────────
  {
    id: 'mock-008',
    municipio: 'Recife',
    uf: 'PE',
    regiao: 'nordeste',
    hospital: 'Hospital da Restauração',
    categoria: 'imagem',
    descricao: 'Aquisição de mamógrafo digital com tomossíntese e estação de laudo',
    score: 84,
    subScores: { convenio: 80, historico: 75, orgao: 85, competicao: 70 },
    valorEstimado: 1_200_000,
    janelaEmDias: 45,
    urgencia: 'media',
    status: 'quente',
    probabilidadeEdital: 1.0,
    concorrentes: [],
    indiceConcorrencia: 'medio',
    acaoRecomendada: 'Edital publicado — monitorar e preparar proposta.',
    licitacaoRelacionada: {
      id: 'PNCP-PE-2026-001',
      numeroControlePNCP: '05839.001/2026-001',
      orgaoEntidade: { cnpj: '05839567000180', razaoSocial: 'Hospital da Restauração', municipio: 'Recife', uf: 'PE' },
      modalidadeNome: 'Pregão Eletrônico',
      objetoCompra: 'Aquisição de mamógrafo digital com tomossíntese e estação de laudo',
      valorTotalEstimado: 1_200_000,
      dataPublicacaoPncp: daysAgo(5),
      dataEncerramentoProposta: daysFromNow(45),
      situacaoCompraId: 1,
      situacaoCompraNome: 'Publicada',
      linkSistemaOrigem: 'https://www.comprasnet.gov.br',
    },
    createdAt: daysAgo(5),
    updatedAt: daysAgo(1),
  },
  {
    id: 'mock-009',
    municipio: 'Fortaleza',
    uf: 'CE',
    regiao: 'nordeste',
    hospital: 'Hospital Geral de Fortaleza',
    categoria: 'laboratorio',
    descricao: 'Aquisição de centrífugas refrigeradas de alta velocidade e equipamentos auxiliares',
    score: 80,
    subScores: { convenio: 75, historico: 72, orgao: 80, competicao: 65 },
    valorEstimado: 620_000,
    janelaEmDias: 38,
    urgencia: 'media',
    status: 'quente',
    probabilidadeEdital: 1.0,
    concorrentes: [],
    indiceConcorrencia: 'baixo',
    acaoRecomendada: 'Edital publicado — monitorar e preparar proposta.',
    licitacaoRelacionada: {
      id: 'PNCP-CE-2026-001',
      numeroControlePNCP: '07953.001/2026-001',
      orgaoEntidade: { cnpj: '07953613000188', razaoSocial: 'Hospital Geral de Fortaleza', municipio: 'Fortaleza', uf: 'CE' },
      modalidadeNome: 'Pregão Eletrônico',
      objetoCompra: 'Aquisição de centrífugas refrigeradas de alta velocidade para laboratório clínico',
      valorTotalEstimado: 620_000,
      dataPublicacaoPncp: daysAgo(7),
      dataEncerramentoProposta: daysFromNow(38),
      situacaoCompraId: 1,
      situacaoCompraNome: 'Publicada',
      linkSistemaOrigem: 'https://www.comprasnet.gov.br',
    },
    createdAt: daysAgo(7),
    updatedAt: daysAgo(2),
  },
  {
    id: 'mock-010',
    municipio: 'Curitiba',
    uf: 'PR',
    regiao: 'sul',
    hospital: 'Hospital de Clínicas da UFPR',
    categoria: 'cirurgia',
    descricao: 'Aquisição de sistema de videolaparoscopia 4K com torre cirúrgica completa',
    score: 86,
    subScores: { convenio: 82, historico: 80, orgao: 88, competicao: 76 },
    valorEstimado: 2_400_000,
    janelaEmDias: 52,
    urgencia: 'media',
    status: 'quente',
    probabilidadeEdital: 1.0,
    concorrentes: [],
    indiceConcorrencia: 'medio',
    acaoRecomendada: 'Edital publicado — monitorar e preparar proposta técnica.',
    licitacaoRelacionada: {
      id: 'PNCP-PR-2026-001',
      numeroControlePNCP: '75117.001/2026-001',
      orgaoEntidade: { cnpj: '75117560000118', razaoSocial: 'Hospital de Clínicas da UFPR', municipio: 'Curitiba', uf: 'PR' },
      modalidadeNome: 'Pregão Eletrônico',
      objetoCompra: 'Aquisição de sistema de videolaparoscopia 4K com torre cirúrgica completa para CC',
      valorTotalEstimado: 2_400_000,
      dataPublicacaoPncp: daysAgo(3),
      dataEncerramentoProposta: daysFromNow(52),
      situacaoCompraId: 1,
      situacaoCompraNome: 'Publicada',
      linkSistemaOrigem: 'https://www.comprasnet.gov.br',
    },
    createdAt: daysAgo(3),
    updatedAt: daysAgo(1),
  },
  {
    id: 'mock-011',
    municipio: 'Goiânia',
    uf: 'GO',
    regiao: 'centro-oeste',
    hospital: 'Hospital de Urgências de Goiânia',
    categoria: 'uti',
    descricao: 'Contratação de bomba de infusão seringa e volumétrica para UTI (60 unidades)',
    score: 82,
    subScores: { convenio: 78, historico: 75, orgao: 82, competicao: 68 },
    valorEstimado: 780_000,
    janelaEmDias: 60,
    urgencia: 'media',
    status: 'quente',
    probabilidadeEdital: 1.0,
    concorrentes: [],
    indiceConcorrencia: 'baixo',
    acaoRecomendada: 'Edital publicado — monitorar e preparar proposta.',
    licitacaoRelacionada: {
      id: 'PNCP-GO-2026-001',
      numeroControlePNCP: '01409.001/2026-001',
      orgaoEntidade: { cnpj: '01409660000131', razaoSocial: 'Hospital de Urgências de Goiânia', municipio: 'Goiânia', uf: 'GO' },
      modalidadeNome: 'Pregão Eletrônico',
      objetoCompra: 'Contratação de bomba de infusão seringa e volumétrica para UTI',
      valorTotalEstimado: 780_000,
      dataPublicacaoPncp: daysAgo(15),
      dataEncerramentoProposta: daysFromNow(60),
      situacaoCompraId: 1,
      situacaoCompraNome: 'Publicada',
      linkSistemaOrigem: 'https://www.comprasnet.gov.br',
    },
    createdAt: daysAgo(15),
    updatedAt: daysAgo(3),
  },
  {
    id: 'mock-012',
    municipio: 'Manaus',
    uf: 'AM',
    regiao: 'norte',
    hospital: 'Hospital e Pronto-Socorro João Lúcio',
    categoria: 'imagem',
    descricao: 'Aquisição de equipamento de ultrassom portátil com transdutor convexo e linear',
    score: 79,
    subScores: { convenio: 75, historico: 70, orgao: 80, competicao: 68 },
    valorEstimado: 450_000,
    janelaEmDias: 42,
    urgencia: 'media',
    status: 'quente',
    probabilidadeEdital: 1.0,
    concorrentes: [],
    indiceConcorrencia: 'baixo',
    acaoRecomendada: 'Edital publicado — monitorar e preparar proposta.',
    licitacaoRelacionada: {
      id: 'PNCP-AM-2026-001',
      numeroControlePNCP: '04629.001/2026-001',
      orgaoEntidade: { cnpj: '04629489000140', razaoSocial: 'Hospital e Pronto-Socorro João Lúcio', municipio: 'Manaus', uf: 'AM' },
      modalidadeNome: 'Pregão Eletrônico',
      objetoCompra: 'Aquisição de equipamento de ultrassom portátil com transdutor convexo e linear',
      valorTotalEstimado: 450_000,
      dataPublicacaoPncp: daysAgo(18),
      dataEncerramentoProposta: daysFromNow(42),
      situacaoCompraId: 1,
      situacaoCompraNome: 'Publicada',
      linkSistemaOrigem: 'https://www.comprasnet.gov.br',
    },
    createdAt: daysAgo(18),
    updatedAt: daysAgo(4),
  },
  // ── HISTÓRICO (encerrados — inteligência de mercado) ─────────────────────
  {
    id: 'mock-013',
    municipio: 'São Paulo',
    uf: 'SP',
    regiao: 'sudeste',
    hospital: 'Instituto do Coração — InCor',
    categoria: 'imagem',
    descricao: 'Tomógrafo computadorizado 256 canais — ciclo anterior 2025',
    score: 85,
    subScores: { convenio: 80, historico: 88, orgao: 90, competicao: 72 },
    valorEstimado: 4_200_000,
    janelaEmDias: 365 * 3,
    urgencia: 'alta',
    status: 'quente',
    probabilidadeEdital: 0.75,
    concorrentes: [],
    indiceConcorrencia: 'alto',
    acaoRecomendada: 'Comprou em 2025 — próximo ciclo estimado para 2028. Mapear contato agora.',
    licitacaoRelacionada: {
      id: 'PNCP-SP-2025-001',
      numeroControlePNCP: '63025.001/2025-001',
      orgaoEntidade: { cnpj: '63025530000104', razaoSocial: 'Instituto do Coração — InCor', municipio: 'São Paulo', uf: 'SP' },
      modalidadeNome: 'Concorrência',
      objetoCompra: 'Tomógrafo computadorizado 256 canais com mesa flutuante e software avançado de pós-processamento',
      valorTotalEstimado: 4_200_000,
      dataPublicacaoPncp: daysAgo(180),
      dataEncerramentoProposta: daysAgo(150),
      situacaoCompraId: 3,
      situacaoCompraNome: 'Encerrada',
      linkSistemaOrigem: 'https://www.comprasnet.gov.br',
    },
    createdAt: daysAgo(180),
    updatedAt: daysAgo(150),
  },
  {
    id: 'mock-014',
    municipio: 'Rio de Janeiro',
    uf: 'RJ',
    regiao: 'sudeste',
    hospital: 'Hospital Nacional de Traumatologia e Ortopedia',
    categoria: 'cirurgia',
    descricao: 'Autoclave de grande porte para central de material esterilizado (3 unidades)',
    score: 78,
    subScores: { convenio: 72, historico: 75, orgao: 80, competicao: 65 },
    valorEstimado: 890_000,
    janelaEmDias: 365 * 2,
    urgencia: 'media',
    status: 'morno',
    probabilidadeEdital: 0.7,
    concorrentes: [],
    indiceConcorrencia: 'medio',
    acaoRecomendada: 'Comprou em 2024 — próximo ciclo estimado para 2026. Entrar em contato.',
    licitacaoRelacionada: {
      id: 'PNCP-RJ-2024-001',
      numeroControlePNCP: '33910.001/2024-001',
      orgaoEntidade: { cnpj: '33910894000171', razaoSocial: 'Hospital Nacional de Traumatologia e Ortopedia', municipio: 'Rio de Janeiro', uf: 'RJ' },
      modalidadeNome: 'Pregão Eletrônico',
      objetoCompra: 'Autoclave de grande porte horizontal para central de material esterilizado',
      valorTotalEstimado: 890_000,
      dataPublicacaoPncp: daysAgo(360),
      dataEncerramentoProposta: daysAgo(330),
      situacaoCompraId: 3,
      situacaoCompraNome: 'Encerrada',
      linkSistemaOrigem: 'https://www.comprasnet.gov.br',
    },
    createdAt: daysAgo(360),
    updatedAt: daysAgo(330),
  },
  {
    id: 'mock-015',
    municipio: 'Florianópolis',
    uf: 'SC',
    regiao: 'sul',
    hospital: 'Hospital Universitário da UFSC',
    categoria: 'laboratorio',
    descricao: 'Sistema de automação laboratorial completo com analisadores bioquímico e imunológico',
    score: 83,
    subScores: { convenio: 80, historico: 82, orgao: 85, competicao: 70 },
    valorEstimado: 3_100_000,
    janelaEmDias: 365 * 3,
    urgencia: 'alta',
    status: 'quente',
    probabilidadeEdital: 0.75,
    concorrentes: [],
    indiceConcorrencia: 'medio',
    acaoRecomendada: 'Comprou em 2025 — próximo ciclo estimado para 2028. Mapear laboratório.',
    licitacaoRelacionada: {
      id: 'PNCP-SC-2025-001',
      numeroControlePNCP: '83899.001/2025-001',
      orgaoEntidade: { cnpj: '83899526000182', razaoSocial: 'Hospital Universitário da UFSC', municipio: 'Florianópolis', uf: 'SC' },
      modalidadeNome: 'Pregão Eletrônico',
      objetoCompra: 'Sistema de automação laboratorial com analisadores bioquímico e imunológico integrados',
      valorTotalEstimado: 3_100_000,
      dataPublicacaoPncp: daysAgo(200),
      dataEncerramentoProposta: daysAgo(170),
      situacaoCompraId: 3,
      situacaoCompraNome: 'Encerrada',
      linkSistemaOrigem: 'https://www.comprasnet.gov.br',
    },
    createdAt: daysAgo(200),
    updatedAt: daysAgo(170),
  },
  {
    id: 'mock-016',
    municipio: 'Natal',
    uf: 'RN',
    regiao: 'nordeste',
    hospital: 'Hospital Universitário Onofre Lopes',
    categoria: 'oncologia',
    descricao: 'Aquisição de sistema PET-CT para diagnóstico oncológico avançado',
    score: 76,
    subScores: { convenio: 72, historico: 74, orgao: 78, competicao: 60 },
    valorEstimado: 6_800_000,
    janelaEmDias: 365 * 2,
    urgencia: 'media',
    status: 'morno',
    probabilidadeEdital: 0.65,
    concorrentes: [],
    indiceConcorrencia: 'baixo',
    acaoRecomendada: 'Comprou em 2024 — próximo ciclo estimado para 2026. Mapear contato.',
    licitacaoRelacionada: {
      id: 'PNCP-RN-2024-001',
      numeroControlePNCP: '24340.001/2024-001',
      orgaoEntidade: { cnpj: '24365160000108', razaoSocial: 'Hospital Universitário Onofre Lopes', municipio: 'Natal', uf: 'RN' },
      modalidadeNome: 'Concorrência',
      objetoCompra: 'Aquisição de sistema PET-CT para diagnóstico oncológico',
      valorTotalEstimado: 6_800_000,
      dataPublicacaoPncp: daysAgo(400),
      dataEncerramentoProposta: daysAgo(370),
      situacaoCompraId: 3,
      situacaoCompraNome: 'Encerrada',
      linkSistemaOrigem: 'https://www.comprasnet.gov.br',
    },
    createdAt: daysAgo(400),
    updatedAt: daysAgo(370),
  },
  {
    id: 'mock-017',
    municipio: 'Belém',
    uf: 'PA',
    regiao: 'norte',
    hospital: 'Hospital Universitário João de Barros Barreto',
    categoria: 'uti',
    descricao: 'Oxímetros de pulso de dedo portáteis e de mesa para UTI (80 unidades)',
    score: 72,
    subScores: { convenio: 68, historico: 70, orgao: 74, competicao: 62 },
    valorEstimado: 320_000,
    janelaEmDias: 365 * 2,
    urgencia: 'normal',
    status: 'morno',
    probabilidadeEdital: 0.65,
    concorrentes: [],
    indiceConcorrencia: 'baixo',
    acaoRecomendada: 'Comprou em 2024 — próximo ciclo 2026. Monitorar edital.',
    licitacaoRelacionada: {
      id: 'PNCP-PA-2024-001',
      numeroControlePNCP: '05078.001/2024-001',
      orgaoEntidade: { cnpj: '05078849000174', razaoSocial: 'Hospital Universitário João de Barros Barreto', municipio: 'Belém', uf: 'PA' },
      modalidadeNome: 'Pregão Eletrônico',
      objetoCompra: 'Oxímetros de pulso de dedo portáteis e de mesa para monitoração em UTI',
      valorTotalEstimado: 320_000,
      dataPublicacaoPncp: daysAgo(420),
      dataEncerramentoProposta: daysAgo(390),
      situacaoCompraId: 3,
      situacaoCompraNome: 'Encerrada',
      linkSistemaOrigem: 'https://www.comprasnet.gov.br',
    },
    createdAt: daysAgo(420),
    updatedAt: daysAgo(390),
  },
  {
    id: 'mock-018',
    municipio: 'Maceió',
    uf: 'AL',
    regiao: 'nordeste',
    hospital: 'Hospital Universitário Prof. Alberto Antunes',
    categoria: 'imagem',
    descricao: 'Aquisição de raio-X digital fixo com detector flat panel para emergência',
    score: 74,
    subScores: { convenio: 70, historico: 72, orgao: 76, competicao: 64 },
    valorEstimado: 760_000,
    janelaEmDias: 365 * 2,
    urgencia: 'normal',
    status: 'morno',
    probabilidadeEdital: 0.65,
    concorrentes: [],
    indiceConcorrencia: 'medio',
    acaoRecomendada: 'Comprou em 2024 — próximo ciclo 2026. Mapear contato.',
    licitacaoRelacionada: {
      id: 'PNCP-AL-2024-001',
      numeroControlePNCP: '12200.001/2024-001',
      orgaoEntidade: { cnpj: '12200518000195', razaoSocial: 'Hospital Universitário Prof. Alberto Antunes', municipio: 'Maceió', uf: 'AL' },
      modalidadeNome: 'Pregão Eletrônico',
      objetoCompra: 'Aquisição de raio-X digital fixo com detector flat panel para sala de emergência',
      valorTotalEstimado: 760_000,
      dataPublicacaoPncp: daysAgo(440),
      dataEncerramentoProposta: daysAgo(410),
      situacaoCompraId: 3,
      situacaoCompraNome: 'Encerrada',
      linkSistemaOrigem: 'https://www.comprasnet.gov.br',
    },
    createdAt: daysAgo(440),
    updatedAt: daysAgo(410),
  },
  {
    id: 'mock-019',
    municipio: 'Campo Grande',
    uf: 'MS',
    regiao: 'centro-oeste',
    hospital: 'Hospital Universitário Maria Aparecida Pedrossian',
    categoria: 'cirurgia',
    descricao: 'Aquisição de sistema robótico para cirurgia minimamente invasiva',
    score: 88,
    subScores: { convenio: 85, historico: 86, orgao: 90, competicao: 60 },
    valorEstimado: 12_500_000,
    janelaEmDias: 365 * 3,
    urgencia: 'alta',
    status: 'quente',
    probabilidadeEdital: 0.75,
    concorrentes: [],
    indiceConcorrencia: 'baixo',
    acaoRecomendada: 'Comprou em 2025 — próximo ciclo estimado para 2028. Iniciar relacionamento.',
    licitacaoRelacionada: {
      id: 'PNCP-MS-2025-001',
      numeroControlePNCP: '15414.001/2025-001',
      orgaoEntidade: { cnpj: '15414710000116', razaoSocial: 'Hospital Universitário Maria Aparecida Pedrossian', municipio: 'Campo Grande', uf: 'MS' },
      modalidadeNome: 'Concorrência',
      objetoCompra: 'Aquisição de sistema robótico para cirurgia minimamente invasiva com instrumentais',
      valorTotalEstimado: 12_500_000,
      dataPublicacaoPncp: daysAgo(220),
      dataEncerramentoProposta: daysAgo(190),
      situacaoCompraId: 3,
      situacaoCompraNome: 'Encerrada',
      linkSistemaOrigem: 'https://www.comprasnet.gov.br',
    },
    createdAt: daysAgo(220),
    updatedAt: daysAgo(190),
  },
  {
    id: 'mock-020',
    municipio: 'João Pessoa',
    uf: 'PB',
    regiao: 'nordeste',
    hospital: 'Hospital Universitário Lauro Wanderley',
    categoria: 'laboratorio',
    descricao: 'Aquisição de gasômetro e coagulômetro para laboratório de urgência',
    score: 70,
    subScores: { convenio: 66, historico: 68, orgao: 72, competicao: 60 },
    valorEstimado: 410_000,
    janelaEmDias: 365 * 2,
    urgencia: 'normal',
    status: 'frio',
    probabilidadeEdital: 0.60,
    concorrentes: [],
    indiceConcorrencia: 'baixo',
    acaoRecomendada: 'Comprou em 2024 — próximo ciclo 2026. Monitorar.',
    licitacaoRelacionada: {
      id: 'PNCP-PB-2024-001',
      numeroControlePNCP: '08842.001/2024-001',
      orgaoEntidade: { cnpj: '08842505000181', razaoSocial: 'Hospital Universitário Lauro Wanderley', municipio: 'João Pessoa', uf: 'PB' },
      modalidadeNome: 'Pregão Eletrônico',
      objetoCompra: 'Aquisição de gasômetro e coagulômetro para laboratório de urgência',
      valorTotalEstimado: 410_000,
      dataPublicacaoPncp: daysAgo(460),
      dataEncerramentoProposta: daysAgo(430),
      situacaoCompraId: 3,
      situacaoCompraNome: 'Encerrada',
      linkSistemaOrigem: 'https://www.comprasnet.gov.br',
    },
    createdAt: daysAgo(460),
    updatedAt: daysAgo(430),
  },
]

// ── Vencedores / Concorrentes ──────────────────────────────────────────────────

export const MOCK_VENCEDORES: MockVencedor[] = [
  { cnpj: '56989570000108', nome: 'Siemens Healthineers Brasil Ltda', vitorias: 38, valorTotal: 42_800_000 },
  { cnpj: '60872504000123', nome: 'GE Healthcare do Brasil Ltda', vitorias: 31, valorTotal: 36_500_000 },
  { cnpj: '72613663000168', nome: 'Philips Medical Systems Ltda', vitorias: 27, valorTotal: 28_900_000 },
  { cnpj: '45543915000155', nome: 'Drager Brasil Ltda', vitorias: 24, valorTotal: 18_200_000 },
  { cnpj: '10831365000183', nome: 'Mindray do Brasil Importação e Exportação Ltda', vitorias: 22, valorTotal: 14_600_000 },
  { cnpj: '03584540000144', nome: 'Medtronic Comercial Ltda', vitorias: 19, valorTotal: 22_400_000 },
  { cnpj: '07591338000176', nome: 'Roche Diagnóstica Brasil Ltda', vitorias: 17, valorTotal: 11_800_000 },
  { cnpj: '43206351000100', nome: 'Carestream Health do Brasil Ltda', vitorias: 15, valorTotal: 9_200_000 },
  { cnpj: '68028769000103', nome: 'Shimadzu do Brasil Comércio Ltda', vitorias: 13, valorTotal: 8_400_000 },
  { cnpj: '92649301000108', nome: 'Intermed Equipamento Médico Hospitalar', vitorias: 12, valorTotal: 7_600_000 },
]

// ── Preços de referência (Compras.gov) ────────────────────────────────────────

export const MOCK_PRECOS: MockPreco[] = [
  {
    id: 'p-001', codigoItem: '10561', descricaoItem: 'Tomógrafo Computadorizado 64 Canais', unidadeMedida: 'UN',
    valorUnitario: 1_850_000, quantidade: 1, valorTotal: 1_850_000,
    dataResultado: daysAgo(45), nomeOrgao: 'Hospital das Clínicas FMUSP', siglaUf: 'SP', municipio: 'São Paulo',
    cnpjFornecedor: '56989570000108', razaoSocialFornecedor: 'Siemens Healthineers Brasil Ltda',
    numeroDocumento: 'CT-2026/0023', origem: 'contrato',
  },
  {
    id: 'p-002', codigoItem: '10561', descricaoItem: 'Tomógrafo Computadorizado 128 Canais', unidadeMedida: 'UN',
    valorUnitario: 2_400_000, quantidade: 1, valorTotal: 2_400_000,
    dataResultado: daysAgo(90), nomeOrgao: 'Hospital Universitário da UFMG', siglaUf: 'MG', municipio: 'Belo Horizonte',
    cnpjFornecedor: '60872504000123', razaoSocialFornecedor: 'GE Healthcare do Brasil Ltda',
    numeroDocumento: 'CT-2025/0154', origem: 'contrato',
  },
  {
    id: 'p-003', codigoItem: '10562', descricaoItem: 'Ressonância Magnética 1.5 Tesla', unidadeMedida: 'UN',
    valorUnitario: 3_200_000, quantidade: 1, valorTotal: 3_200_000,
    dataResultado: daysAgo(120), nomeOrgao: 'Hospital de Clínicas de Porto Alegre', siglaUf: 'RS', municipio: 'Porto Alegre',
    cnpjFornecedor: '72613663000168', razaoSocialFornecedor: 'Philips Medical Systems Ltda',
    numeroDocumento: 'ARP-2025/0067', origem: 'ata',
  },
  {
    id: 'p-004', codigoItem: '10562', descricaoItem: 'Ressonância Magnética 3.0 Tesla', unidadeMedida: 'UN',
    valorUnitario: 5_600_000, quantidade: 1, valorTotal: 5_600_000,
    dataResultado: daysAgo(200), nomeOrgao: 'Instituto do Coração — InCor', siglaUf: 'SP', municipio: 'São Paulo',
    cnpjFornecedor: '60872504000123', razaoSocialFornecedor: 'GE Healthcare do Brasil Ltda',
    numeroDocumento: 'CT-2025/0012', origem: 'contrato',
  },
  {
    id: 'p-005', codigoItem: '10580', descricaoItem: 'Ventilador Pulmonar UTI Adulto', unidadeMedida: 'UN',
    valorUnitario: 52_000, quantidade: 10, valorTotal: 520_000,
    dataResultado: daysAgo(30), nomeOrgao: 'Hospital Federal de Ipanema', siglaUf: 'RJ', municipio: 'Rio de Janeiro',
    cnpjFornecedor: '45543915000155', razaoSocialFornecedor: 'Drager Brasil Ltda',
    numeroDocumento: 'ARP-2026/0011', origem: 'ata',
  },
  {
    id: 'p-006', codigoItem: '10580', descricaoItem: 'Ventilador Pulmonar Neonatal', unidadeMedida: 'UN',
    valorUnitario: 68_000, quantidade: 5, valorTotal: 340_000,
    dataResultado: daysAgo(60), nomeOrgao: 'Hospital da Criança Santo Antônio', siglaUf: 'RS', municipio: 'Porto Alegre',
    cnpjFornecedor: '10831365000183', razaoSocialFornecedor: 'Mindray do Brasil Ltda',
    numeroDocumento: 'ARP-2025/0189', origem: 'ata',
  },
  {
    id: 'p-007', codigoItem: '10590', descricaoItem: 'Monitor Multiparamétrico Adulto', unidadeMedida: 'UN',
    valorUnitario: 24_500, quantidade: 20, valorTotal: 490_000,
    dataResultado: daysAgo(15), nomeOrgao: 'Hospital Regional de Taguatinga', siglaUf: 'DF', municipio: 'Brasília',
    cnpjFornecedor: '10831365000183', razaoSocialFornecedor: 'Mindray do Brasil Ltda',
    numeroDocumento: 'CT-2026/0041', origem: 'contrato',
  },
  {
    id: 'p-008', codigoItem: '10595', descricaoItem: 'Bomba de Infusão Seringa', unidadeMedida: 'UN',
    valorUnitario: 8_200, quantidade: 30, valorTotal: 246_000,
    dataResultado: daysAgo(22), nomeOrgao: 'Hospital de Urgências de Goiânia', siglaUf: 'GO', municipio: 'Goiânia',
    cnpjFornecedor: '03584540000144', razaoSocialFornecedor: 'Medtronic Comercial Ltda',
    numeroDocumento: 'ARP-2026/0008', origem: 'ata',
  },
  {
    id: 'p-009', codigoItem: '10600', descricaoItem: 'Analisador Hematológico 6 Parâmetros', unidadeMedida: 'UN',
    valorUnitario: 98_000, quantidade: 2, valorTotal: 196_000,
    dataResultado: daysAgo(50), nomeOrgao: 'Santa Casa de Misericórdia de BH', siglaUf: 'MG', municipio: 'Belo Horizonte',
    cnpjFornecedor: '07591338000176', razaoSocialFornecedor: 'Roche Diagnóstica Brasil Ltda',
    numeroDocumento: 'CT-2026/0029', origem: 'contrato',
  },
  {
    id: 'p-010', codigoItem: '10610', descricaoItem: 'Mesa Cirúrgica Elétrica Multiposicional', unidadeMedida: 'UN',
    valorUnitario: 185_000, quantidade: 5, valorTotal: 925_000,
    dataResultado: daysAgo(75), nomeOrgao: 'Hospital Geral Roberto Santos', siglaUf: 'BA', municipio: 'Salvador',
    cnpjFornecedor: '56989570000108', razaoSocialFornecedor: 'Siemens Healthineers Brasil Ltda',
    numeroDocumento: 'ARP-2025/0201', origem: 'ata',
  },
  {
    id: 'p-011', codigoItem: '10620', descricaoItem: 'Autoclave Horizontal 134L', unidadeMedida: 'UN',
    valorUnitario: 145_000, quantidade: 3, valorTotal: 435_000,
    dataResultado: daysAgo(100), nomeOrgao: 'Hospital Regional de Sobradinho', siglaUf: 'DF', municipio: 'Brasília',
    cnpjFornecedor: '43206351000100', razaoSocialFornecedor: 'Carestream Health do Brasil Ltda',
    numeroDocumento: 'CT-2025/0098', origem: 'contrato',
  },
  {
    id: 'p-012', codigoItem: '10630', descricaoItem: 'Mamógrafo Digital com Tomossíntese', unidadeMedida: 'UN',
    valorUnitario: 950_000, quantidade: 1, valorTotal: 950_000,
    dataResultado: daysAgo(40), nomeOrgao: 'Hospital da Restauração', siglaUf: 'PE', municipio: 'Recife',
    cnpjFornecedor: '60872504000123', razaoSocialFornecedor: 'GE Healthcare do Brasil Ltda',
    numeroDocumento: 'ARP-2026/0015', origem: 'ata',
  },
]
