CREATE TEMP TABLE w ON COMMIT DROP AS SELECT c.cnpj_orgao org, c.categoria_saude cat, r.ni_fornecedor forn, c.numero_controle_pncp ncp, coalesce(r.ano, extract(year from r.data_resultado)::int) ano, r.data_resultado dt, CASE WHEN i.valor_unitario_estimado > 0 AND r.valor_unitario_homologado <> i.valor_unitario_estimado AND r.valor_unitario_homologado / i.valor_unitario_estimado > 0.05 AND r.valor_unitario_homologado / i.valor_unitario_estimado <= 1.5 THEN r.valor_unitario_homologado / i.valor_unitario_estimado END ratio FROM resultados r JOIN itens i ON i.numero_controle_pncp = r.numero_controle_pncp AND i.numero_item = r.numero_item JOIN contratacoes c ON c.numero_controle_pncp = r.numero_controle_pncp WHERE c.modalidade_nome LIKE 'Pregão%' AND r.valor_unitario_homologado > 0 AND c.categoria_saude IN ('medicamento','material_hospitalar');
-- Q28 cobertura (med+material, pregões abertos) por mínimo de pregões distintos no recorte
WITH ab AS (SELECT c.cnpj_orgao org, c.categoria_saude cat FROM contratacoes c WHERE c.data_encerramento_proposta >= current_date AND c.modalidade_nome LIKE 'Pregão%' AND c.categoria_saude IN ('medicamento','material_hospitalar') AND NOT EXISTS (SELECT 1 FROM resultados r WHERE r.numero_controle_pncp = c.numero_controle_pncp)),
oc AS (SELECT org, cat, count(ratio) nv, count(*) ni, count(DISTINCT forn) nf, count(DISTINCT ncp) FILTER (WHERE ratio IS NOT NULL) nl FROM w WHERE dt >= current_date - 730 GROUP BY 1,2)
SELECT count(*) abertas, count(*) FILTER (WHERE nv >= 30) d_l1, count(*) FILTER (WHERE nv >= 30 AND nl >= 3) d_l3, count(*) FILTER (WHERE nv >= 30 AND nl >= 5) d_l5, count(*) FILTER (WHERE ni >= 10 AND nf >= 3) conc, count(*) FILTER (WHERE (nv >= 30 AND nl >= 3) OR (ni >= 10 AND nf >= 3)) algum_l3, count(*) FILTER (WHERE (nv >= 30 AND nl >= 5) OR (ni >= 10 AND nf >= 3)) algum_l5 FROM ab LEFT JOIN oc USING (org, cat);
-- Q29 backtest med+material: faixa 2025 por órgão+cat com >=1, >=3, >=5 pregões, contra 2026
WITH g AS (SELECT org, cat, count(*) n, count(DISTINCT ncp) nl, percentile_cont(0.25) WITHIN GROUP (ORDER BY ratio) lo, percentile_cont(0.5) WITHIN GROUP (ORDER BY ratio) m, percentile_cont(0.75) WITHIN GROUP (ORDER BY ratio) hi FROM w WHERE ano = 2025 AND ratio IS NOT NULL GROUP BY 1,2 HAVING count(*) >= 30),
mc AS (SELECT cat, percentile_cont(0.5) WITHIN GROUP (ORDER BY ratio) m FROM w WHERE ano = 2025 AND ratio IS NOT NULL GROUP BY cat),
t AS (SELECT * FROM w WHERE ano = 2026 AND ratio IS NOT NULL)
SELECT faixa, count(*) itens, round(100.0*avg((t.ratio BETWEEN g.lo AND g.hi)::int),1) dentro, round(avg(g.hi-g.lo)::numeric,3) largura, round(percentile_cont(0.5) WITHIN GROUP (ORDER BY abs(t.ratio-g.m))::numeric,3) erro_orgao, round(percentile_cont(0.5) WITHIN GROUP (ORDER BY abs(t.ratio-mc.m))::numeric,3) erro_cat_nacional
FROM t JOIN g USING (org, cat) JOIN mc USING (cat) CROSS JOIN LATERAL (VALUES ('>=1 pregão', g.nl >= 1), ('1-2 pregões', g.nl < 3), ('>=3 pregões', g.nl >= 3), ('>=5 pregões', g.nl >= 5)) AS f(faixa, ok) WHERE ok GROUP BY faixa ORDER BY faixa
