CREATE TEMP TABLE b ON COMMIT DROP AS SELECT r.numero_controle_pncp ncp, r.numero_item, r.ni_fornecedor, r.ordem_classificacao_srp srp, r.valor_unitario_homologado h, i.valor_unitario_estimado e, i.codigo_pdm, i.pdm_metodo, c.categoria_saude cat, c.uf, c.modalidade_nome modal, c.esfera, coalesce(r.ano, extract(year from r.data_resultado)::int) ano, CASE WHEN i.valor_unitario_estimado > 0 AND r.valor_unitario_homologado > 0 THEN r.valor_unitario_homologado / i.valor_unitario_estimado END ratio FROM resultados r JOIN itens i ON i.numero_controle_pncp = r.numero_controle_pncp AND i.numero_item = r.numero_item JOIN contratacoes c ON c.numero_controle_pncp = r.numero_controle_pncp;
-- Q1 cobertura geral e sanidade da razão homologado/estimado
SELECT count(*) resultados, count(ratio) com_ambos_valores, round(100.0*count(ratio)/count(*),1) pct_ambos, count(*) FILTER (WHERE ratio = 1) ratio_exato_1, count(*) FILTER (WHERE ratio > 0.05 AND ratio <= 1.5) plausiveis, count(*) FILTER (WHERE ratio > 1.5) acima_1_5, count(*) FILTER (WHERE ratio <= 0.05) abaixo_0_05, count(DISTINCT (ncp, numero_item)) itens_distintos, count(*) FILTER (WHERE srp > 1) srp_ordem_maior_1 FROM b;
-- Q2 distribuição da razão (só plausíveis)
SELECT round(percentile_cont(0.05) WITHIN GROUP (ORDER BY ratio)::numeric,3) p05, round(percentile_cont(0.25) WITHIN GROUP (ORDER BY ratio)::numeric,3) p25, round(percentile_cont(0.5) WITHIN GROUP (ORDER BY ratio)::numeric,3) p50, round(percentile_cont(0.75) WITHIN GROUP (ORDER BY ratio)::numeric,3) p75, round(percentile_cont(0.95) WITHIN GROUP (ORDER BY ratio)::numeric,3) p95 FROM b WHERE ratio > 0.05 AND ratio <= 1.5 AND ratio <> 1;
-- Q3 por categoria (desconto = 1 - razão)
SELECT cat, count(*) n, round(100*(1-percentile_cont(0.5) WITHIN GROUP (ORDER BY ratio))::numeric,1) desc_mediano_pct, round(100*(1-percentile_cont(0.75) WITHIN GROUP (ORDER BY ratio))::numeric,1) desc_p25_pct, round(100*(1-percentile_cont(0.25) WITHIN GROUP (ORDER BY ratio))::numeric,1) desc_p75_pct FROM b WHERE ratio > 0.05 AND ratio <= 1.5 AND ratio <> 1 GROUP BY cat ORDER BY n DESC;
-- Q4 por ano
SELECT ano, count(*) n, count(ratio) FILTER (WHERE ratio > 0.05 AND ratio <= 1.5) validos FROM b GROUP BY ano ORDER BY ano;
-- Q5 PDM: quantos PDMs têm amostra e quanto do volume cobrem
WITH p AS (SELECT codigo_pdm, count(*) n FROM b WHERE codigo_pdm IS NOT NULL AND ratio > 0.05 AND ratio <= 1.5 AND ratio <> 1 GROUP BY 1) SELECT (SELECT count(*) FROM b WHERE ratio > 0.05 AND ratio <= 1.5 AND ratio <> 1) validos_total, (SELECT count(*) FROM b WHERE codigo_pdm IS NOT NULL AND ratio > 0.05 AND ratio <= 1.5 AND ratio <> 1) validos_com_pdm, count(*) pdms, count(*) FILTER (WHERE n >= 10) pdms_n10, count(*) FILTER (WHERE n >= 30) pdms_n30, sum(n) FILTER (WHERE n >= 10) linhas_em_pdm_n10, sum(n) FILTER (WHERE n >= 30) linhas_em_pdm_n30 FROM p;
-- Q6 fornecedores com histórico de desconto
WITH f AS (SELECT ni_fornecedor, count(*) n FROM b WHERE ratio > 0.05 AND ratio <= 1.5 AND ratio <> 1 GROUP BY 1) SELECT count(*) fornecedores, count(*) FILTER (WHERE n >= 10) f_n10, count(*) FILTER (WHERE n >= 30) f_n30, sum(n) FILTER (WHERE n >= 10) linhas_f_n10, sum(n) total FROM f
