CREATE TEMP TABLE b ON COMMIT DROP AS SELECT r.numero_controle_pncp ncp, r.numero_item, r.ni_fornecedor, r.ordem_classificacao_srp srp, r.valor_unitario_homologado h, i.valor_unitario_estimado e, i.codigo_pdm, i.pdm_metodo, c.categoria_saude cat, c.uf, c.modalidade_nome modal, c.esfera, coalesce(r.ano, extract(year from r.data_resultado)::int) ano, CASE WHEN i.valor_unitario_estimado > 0 AND r.valor_unitario_homologado > 0 THEN r.valor_unitario_homologado / i.valor_unitario_estimado END ratio FROM resultados r JOIN itens i ON i.numero_controle_pncp = r.numero_controle_pncp AND i.numero_item = r.numero_item JOIN contratacoes c ON c.numero_controle_pncp = r.numero_controle_pncp;
CREATE TEMP TABLE v ON COMMIT DROP AS SELECT * FROM b WHERE ratio > 0.05 AND ratio <= 1.5 AND ratio <> 1;
-- Q7 modalidade: de onde vem a razão exatamente 1, e desconto mediano por modalidade
SELECT modal, count(*) n, round(100.0*count(*) FILTER (WHERE ratio = 1)/count(*),1) pct_ratio_1, round(100*(1-percentile_cont(0.5) WITHIN GROUP (ORDER BY ratio) FILTER (WHERE ratio > 0.05 AND ratio <= 1.5 AND ratio <> 1))::numeric,1) desc_med FROM b WHERE ratio IS NOT NULL GROUP BY modal ORDER BY n DESC LIMIT 10;
-- Q8 largura da faixa (p75-p25 da razão): categoria vs PDM vs fornecedor vs fornecedor+PDM (mediana das larguras, grupos com n>=30)
SELECT 'categoria' nivel, count(*) grupos, round(percentile_cont(0.5) WITHIN GROUP (ORDER BY w)::numeric,3) largura_mediana FROM (SELECT cat, percentile_cont(0.75) WITHIN GROUP (ORDER BY ratio) - percentile_cont(0.25) WITHIN GROUP (ORDER BY ratio) w FROM v GROUP BY cat HAVING count(*) >= 30) x
UNION ALL SELECT 'pdm', count(*), round(percentile_cont(0.5) WITHIN GROUP (ORDER BY w)::numeric,3) FROM (SELECT codigo_pdm, percentile_cont(0.75) WITHIN GROUP (ORDER BY ratio) - percentile_cont(0.25) WITHIN GROUP (ORDER BY ratio) w FROM v WHERE codigo_pdm IS NOT NULL GROUP BY 1 HAVING count(*) >= 30) x
UNION ALL SELECT 'pdm+uf', count(*), round(percentile_cont(0.5) WITHIN GROUP (ORDER BY w)::numeric,3) FROM (SELECT codigo_pdm, uf, percentile_cont(0.75) WITHIN GROUP (ORDER BY ratio) - percentile_cont(0.25) WITHIN GROUP (ORDER BY ratio) w FROM v WHERE codigo_pdm IS NOT NULL GROUP BY 1,2 HAVING count(*) >= 30) x
UNION ALL SELECT 'fornecedor', count(*), round(percentile_cont(0.5) WITHIN GROUP (ORDER BY w)::numeric,3) FROM (SELECT ni_fornecedor, percentile_cont(0.75) WITHIN GROUP (ORDER BY ratio) - percentile_cont(0.25) WITHIN GROUP (ORDER BY ratio) w FROM v GROUP BY 1 HAVING count(*) >= 30) x
UNION ALL SELECT 'fornecedor+cat', count(*), round(percentile_cont(0.5) WITHIN GROUP (ORDER BY w)::numeric,3) FROM (SELECT ni_fornecedor, cat, percentile_cont(0.75) WITHIN GROUP (ORDER BY ratio) - percentile_cont(0.25) WITHIN GROUP (ORDER BY ratio) w FROM v GROUP BY 1,2 HAVING count(*) >= 30) x
UNION ALL SELECT 'fornecedor+pdm', count(*), round(percentile_cont(0.5) WITHIN GROUP (ORDER BY w)::numeric,3) FROM (SELECT ni_fornecedor, codigo_pdm, percentile_cont(0.75) WITHIN GROUP (ORDER BY ratio) - percentile_cont(0.25) WITHIN GROUP (ORDER BY ratio) w FROM v WHERE codigo_pdm IS NOT NULL GROUP BY 1,2 HAVING count(*) >= 10) x
UNION ALL SELECT 'orgao(cnpj via ncp)', count(*), round(percentile_cont(0.5) WITHIN GROUP (ORDER BY w)::numeric,3) FROM (SELECT left(ncp,14) org, percentile_cont(0.75) WITHIN GROUP (ORDER BY ratio) - percentile_cont(0.25) WITHIN GROUP (ORDER BY ratio) w FROM v GROUP BY 1 HAVING count(*) >= 30) x;
-- Q9 preço ABSOLUTO dentro do PDM: p75/p25 do homologado (dispersão por unidade misturada)
SELECT count(*) pdms, round(percentile_cont(0.5) WITHIN GROUP (ORDER BY q)::numeric,1) p75_sobre_p25_mediano, round(percentile_cont(0.25) WITHIN GROUP (ORDER BY q)::numeric,1) q_p25, round(percentile_cont(0.75) WITHIN GROUP (ORDER BY q)::numeric,1) q_p75 FROM (SELECT codigo_pdm, percentile_cont(0.75) WITHIN GROUP (ORDER BY h) / nullif(percentile_cont(0.25) WITHIN GROUP (ORDER BY h),0) q FROM b WHERE codigo_pdm IS NOT NULL AND h > 0 GROUP BY 1 HAVING count(*) >= 30) x;
-- Q10 cobertura no PONTO DE USO: itens de licitações abertas (sem resultado, proposta ainda aberta)
WITH ab AS (SELECT i.codigo_pdm, c.categoria_saude cat, c.uf FROM contratacoes c JOIN itens i ON i.numero_controle_pncp = c.numero_controle_pncp WHERE c.data_encerramento_proposta >= current_date AND NOT EXISTS (SELECT 1 FROM resultados r WHERE r.numero_controle_pncp = c.numero_controle_pncp)), pn AS (SELECT codigo_pdm, count(*) n FROM v WHERE codigo_pdm IS NOT NULL GROUP BY 1), pu AS (SELECT codigo_pdm, uf, count(*) n FROM v WHERE codigo_pdm IS NOT NULL GROUP BY 1,2) SELECT count(*) itens_abertos, count(*) FILTER (WHERE ab.codigo_pdm IS NOT NULL) com_pdm, count(*) FILTER (WHERE pn.n >= 10) pdm_n10, count(*) FILTER (WHERE pn.n >= 30) pdm_n30, count(*) FILTER (WHERE pu.n >= 10) pdm_uf_n10 FROM ab LEFT JOIN pn ON pn.codigo_pdm = ab.codigo_pdm LEFT JOIN pu ON pu.codigo_pdm = ab.codigo_pdm AND pu.uf = ab.uf;
-- Q11 previsibilidade do concorrente: o desconto de 2025 prevê o de 2026? (fornecedor com n>=20 nos dois anos)
WITH a AS (SELECT ni_fornecedor, percentile_cont(0.5) WITHIN GROUP (ORDER BY ratio) FILTER (WHERE ano = 2025) m25, percentile_cont(0.5) WITHIN GROUP (ORDER BY ratio) FILTER (WHERE ano = 2026) m26, count(*) FILTER (WHERE ano=2025) n25, count(*) FILTER (WHERE ano=2026) n26 FROM v GROUP BY 1) SELECT count(*) fornecedores, round(corr(m25, m26)::numeric,3) correlacao, round(percentile_cont(0.5) WITHIN GROUP (ORDER BY abs(m26-m25))::numeric,3) dif_abs_mediana, round(percentile_cont(0.8) WITHIN GROUP (ORDER BY abs(m26-m25))::numeric,3) dif_abs_p80 FROM a WHERE n25 >= 20 AND n26 >= 20;
-- Q12 mesma pergunta para o PDM (o mercado do produto é estável?)
WITH a AS (SELECT codigo_pdm, percentile_cont(0.5) WITHIN GROUP (ORDER BY ratio) FILTER (WHERE ano = 2025) m25, percentile_cont(0.5) WITHIN GROUP (ORDER BY ratio) FILTER (WHERE ano = 2026) m26, count(*) FILTER (WHERE ano=2025) n25, count(*) FILTER (WHERE ano=2026) n26 FROM v WHERE codigo_pdm IS NOT NULL GROUP BY 1) SELECT count(*) pdms, round(corr(m25, m26)::numeric,3) correlacao, round(percentile_cont(0.5) WITHIN GROUP (ORDER BY abs(m26-m25))::numeric,3) dif_abs_mediana FROM a WHERE n25 >= 20 AND n26 >= 20
