CREATE TEMP TABLE h ON COMMIT DROP AS SELECT upper(btrim(regexp_replace(regexp_replace(i.descricao, '[^[:alnum:],/%. ]', ' ', 'g'), '\s+', ' ', 'g'))) d, r.valor_unitario_homologado vh, i.valor_unitario_estimado ve, c.categoria_saude cat, c.uf, c.cnpj_orgao org, c.modalidade_nome modal FROM resultados r JOIN itens i ON i.numero_controle_pncp = r.numero_controle_pncp AND i.numero_item = r.numero_item JOIN contratacoes c ON c.numero_controle_pncp = r.numero_controle_pncp WHERE r.valor_unitario_homologado > 0 AND c.modalidade_nome LIKE 'Pregão%';
CREATE INDEX ON h (d);
-- Q13 descrições repetidas no histórico (pregão)
WITH g AS (SELECT d, count(*) n FROM h GROUP BY d) SELECT count(*) descricoes, count(*) FILTER (WHERE n >= 5) d_n5, count(*) FILTER (WHERE n >= 10) d_n10, sum(n) FILTER (WHERE n >= 5) linhas_n5, sum(n) total FROM g;
-- Q14 dispersão do PREÇO ABSOLUTO dentro da mesma descrição (n>=5): p75/p25
SELECT count(*) grupos, round(percentile_cont(0.5) WITHIN GROUP (ORDER BY q)::numeric,2) mediana_p75_p25, round(percentile_cont(0.25) WITHIN GROUP (ORDER BY q)::numeric,2) q25, round(percentile_cont(0.75) WITHIN GROUP (ORDER BY q)::numeric,2) q75, round(percentile_cont(0.9) WITHIN GROUP (ORDER BY q)::numeric,2) q90 FROM (SELECT d, percentile_cont(0.75) WITHIN GROUP (ORDER BY vh) / nullif(percentile_cont(0.25) WITHIN GROUP (ORDER BY vh),0) q FROM h GROUP BY d HAVING count(*) >= 5) x;
-- Q15 PONTO DE USO: itens abertos cuja descrição normalizada tem >=5 / >=10 resultados de pregão
WITH ab AS (SELECT upper(btrim(regexp_replace(regexp_replace(i.descricao, '[^[:alnum:],/%. ]', ' ', 'g'), '\s+', ' ', 'g'))) d, c.categoria_saude cat, c.cnpj_orgao org FROM contratacoes c JOIN itens i ON i.numero_controle_pncp = c.numero_controle_pncp WHERE c.data_encerramento_proposta >= current_date AND NOT EXISTS (SELECT 1 FROM resultados r WHERE r.numero_controle_pncp = c.numero_controle_pncp)), g AS (SELECT d, count(*) n FROM h GROUP BY d), o AS (SELECT org, count(*) n FROM h WHERE ve > 0 AND vh/ve > 0.05 AND vh/ve <= 1.5 AND vh <> ve GROUP BY org) SELECT count(*) itens_abertos, count(*) FILTER (WHERE g.n >= 5) desc_n5, count(*) FILTER (WHERE g.n >= 10) desc_n10, count(*) FILTER (WHERE o.n >= 30) orgao_n30 FROM ab LEFT JOIN g ON g.d = ab.d LEFT JOIN o ON o.org = ab.org;
-- Q16 por categoria: cobertura da descrição idêntica nos itens abertos
WITH ab AS (SELECT upper(btrim(regexp_replace(regexp_replace(i.descricao, '[^[:alnum:],/%. ]', ' ', 'g'), '\s+', ' ', 'g'))) d, c.categoria_saude cat FROM contratacoes c JOIN itens i ON i.numero_controle_pncp = c.numero_controle_pncp WHERE c.data_encerramento_proposta >= current_date AND NOT EXISTS (SELECT 1 FROM resultados r WHERE r.numero_controle_pncp = c.numero_controle_pncp)), g AS (SELECT d, count(*) n FROM h GROUP BY d) SELECT cat, count(*) itens, round(100.0*count(*) FILTER (WHERE g.n >= 5)/count(*),1) pct_desc_n5 FROM ab LEFT JOIN g ON g.d = ab.d GROUP BY cat ORDER BY itens DESC;
-- Q17 largura da razão por órgão+categoria (n>=30)
SELECT count(*) grupos, round(percentile_cont(0.5) WITHIN GROUP (ORDER BY w)::numeric,3) largura_mediana FROM (SELECT org, cat, percentile_cont(0.75) WITHIN GROUP (ORDER BY vh/ve) - percentile_cont(0.25) WITHIN GROUP (ORDER BY vh/ve) w FROM h WHERE ve > 0 AND vh/ve > 0.05 AND vh/ve <= 1.5 AND vh <> ve GROUP BY 1,2 HAVING count(*) >= 30) x;
-- Q18 amostra: 8 descrições frequentes e sua faixa de preço
SELECT left(d, 70) descricao, count(*) n, round(percentile_cont(0.25) WITHIN GROUP (ORDER BY vh)::numeric,2) p25, round(percentile_cont(0.5) WITHIN GROUP (ORDER BY vh)::numeric,2) p50, round(percentile_cont(0.75) WITHIN GROUP (ORDER BY vh)::numeric,2) p75 FROM h GROUP BY d HAVING count(*) >= 40 ORDER BY random() LIMIT 8
