CREATE TEMP TABLE v ON COMMIT DROP AS SELECT c.cnpj_orgao org, c.categoria_saude cat, r.ni_fornecedor forn, coalesce(r.ano, extract(year from r.data_resultado)::int) ano, r.valor_unitario_homologado / i.valor_unitario_estimado ratio FROM resultados r JOIN itens i ON i.numero_controle_pncp = r.numero_controle_pncp AND i.numero_item = r.numero_item JOIN contratacoes c ON c.numero_controle_pncp = r.numero_controle_pncp WHERE c.modalidade_nome LIKE 'Pregão%' AND i.valor_unitario_estimado > 0 AND r.valor_unitario_homologado > 0 AND r.valor_unitario_homologado <> i.valor_unitario_estimado AND r.valor_unitario_homologado / i.valor_unitario_estimado > 0.05 AND r.valor_unitario_homologado / i.valor_unitario_estimado <= 1.5;
-- Q19 backtest: faixa de 2025 (p25-p75) contra resultados de 2026. acerto ~50% = calibrada; largura menor = mais útil
WITH fc AS (SELECT cat, percentile_cont(0.25) WITHIN GROUP (ORDER BY ratio) lo, percentile_cont(0.75) WITHIN GROUP (ORDER BY ratio) hi FROM v WHERE ano = 2025 GROUP BY cat HAVING count(*) >= 30),
fo AS (SELECT org, cat, percentile_cont(0.25) WITHIN GROUP (ORDER BY ratio) lo, percentile_cont(0.75) WITHIN GROUP (ORDER BY ratio) hi FROM v WHERE ano = 2025 GROUP BY org, cat HAVING count(*) >= 30),
ff AS (SELECT forn, cat, percentile_cont(0.25) WITHIN GROUP (ORDER BY ratio) lo, percentile_cont(0.75) WITHIN GROUP (ORDER BY ratio) hi FROM v WHERE ano = 2025 GROUP BY forn, cat HAVING count(*) >= 30),
t AS (SELECT * FROM v WHERE ano = 2026)
SELECT 'categoria' faixa, count(*) testados, round(100.0*avg((t.ratio BETWEEN fc.lo AND fc.hi)::int),1) pct_dentro, round(avg(fc.hi-fc.lo)::numeric,3) largura_media FROM t JOIN fc USING (cat)
UNION ALL SELECT 'orgao+categoria', count(*), round(100.0*avg((t.ratio BETWEEN fo.lo AND fo.hi)::int),1), round(avg(fo.hi-fo.lo)::numeric,3) FROM t JOIN fo USING (org, cat)
UNION ALL SELECT 'categoria (mesmos itens do orgao)', count(*), round(100.0*avg((t.ratio BETWEEN fc.lo AND fc.hi)::int),1), round(avg(fc.hi-fc.lo)::numeric,3) FROM t JOIN fo USING (org, cat) JOIN fc USING (cat)
UNION ALL SELECT 'fornecedor+categoria', count(*), round(100.0*avg((t.ratio BETWEEN ff.lo AND ff.hi)::int),1), round(avg(ff.hi-ff.lo)::numeric,3) FROM t JOIN ff USING (forn, cat)
UNION ALL SELECT 'categoria (mesmos itens do fornecedor)', count(*), round(100.0*avg((t.ratio BETWEEN fc.lo AND fc.hi)::int),1), round(avg(fc.hi-fc.lo)::numeric,3) FROM t JOIN ff USING (forn, cat) JOIN fc USING (cat);
-- Q20 erro absoluto da mediana como previsão (quanto erra, em pontos do estimado)
WITH mc AS (SELECT cat, percentile_cont(0.5) WITHIN GROUP (ORDER BY ratio) m FROM v WHERE ano = 2025 GROUP BY cat HAVING count(*) >= 30), mo AS (SELECT org, cat, percentile_cont(0.5) WITHIN GROUP (ORDER BY ratio) m FROM v WHERE ano = 2025 GROUP BY org, cat HAVING count(*) >= 30), t AS (SELECT * FROM v WHERE ano = 2026)
SELECT count(*) itens, round(percentile_cont(0.5) WITHIN GROUP (ORDER BY abs(t.ratio - mc.m))::numeric,3) erro_mediano_categoria, round(percentile_cont(0.5) WITHIN GROUP (ORDER BY abs(t.ratio - mo.m))::numeric,3) erro_mediano_orgao FROM t JOIN mo USING (org, cat) JOIN mc USING (cat)
