-- índices reais
SELECT tablename, indexname, indexdef FROM pg_indexes WHERE tablename IN ('contratacoes','resultados','itens') ORDER BY 1,2;
CREATE TEMP TABLE v ON COMMIT DROP AS SELECT c.cnpj_orgao org, c.categoria_saude cat, r.ni_fornecedor forn, r.data_resultado dt, r.valor_unitario_homologado / i.valor_unitario_estimado ratio FROM resultados r JOIN itens i ON i.numero_controle_pncp = r.numero_controle_pncp AND i.numero_item = r.numero_item JOIN contratacoes c ON c.numero_controle_pncp = r.numero_controle_pncp WHERE c.modalidade_nome LIKE 'Pregão%' AND i.valor_unitario_estimado > 0 AND r.valor_unitario_homologado > 0 AND r.valor_unitario_homologado <> i.valor_unitario_estimado AND r.valor_unitario_homologado / i.valor_unitario_estimado > 0.05 AND r.valor_unitario_homologado / i.valor_unitario_estimado <= 1.5;
-- Q21 cobertura POR LICITAÇÃO aberta (pregão), janela de 24 meses
WITH ab AS (SELECT c.numero_controle_pncp, c.cnpj_orgao org, c.categoria_saude cat, c.uf, c.valor_total_estimado vt FROM contratacoes c WHERE c.data_encerramento_proposta >= current_date AND c.modalidade_nome LIKE 'Pregão%' AND NOT EXISTS (SELECT 1 FROM resultados r WHERE r.numero_controle_pncp = c.numero_controle_pncp)),
o AS (SELECT org, count(*) n, count(DISTINCT forn) nf FROM v WHERE dt >= current_date - 730 GROUP BY org),
oc AS (SELECT org, cat, count(*) n FROM v WHERE dt >= current_date - 730 GROUP BY org, cat)
SELECT count(*) licitacoes_abertas, count(*) FILTER (WHERE oc.n >= 30) org_cat_n30, count(*) FILTER (WHERE o.n >= 30) org_n30, count(*) FILTER (WHERE o.n >= 30 OR oc.n >= 30) qualquer, count(*) FILTER (WHERE o.nf >= 3) org_3_vencedores, round(100.0*sum(vt) FILTER (WHERE o.n >= 30)/nullif(sum(vt),0),1) pct_valor_org_n30, count(*) FILTER (WHERE o.n >= 10) org_n10 FROM ab LEFT JOIN o USING (org) LEFT JOIN oc USING (org, cat);
-- Q22 mesma cobertura por esfera
WITH ab AS (SELECT c.cnpj_orgao org, c.esfera FROM contratacoes c WHERE c.data_encerramento_proposta >= current_date AND c.modalidade_nome LIKE 'Pregão%' AND NOT EXISTS (SELECT 1 FROM resultados r WHERE r.numero_controle_pncp = c.numero_controle_pncp)), o AS (SELECT org, count(*) n FROM v WHERE dt >= current_date - 730 GROUP BY org) SELECT esfera, count(*) lic, round(100.0*count(*) FILTER (WHERE o.n >= 30)/count(*),1) pct_org_n30 FROM ab LEFT JOIN o USING (org) GROUP BY esfera;
-- Q23 concentração: nos órgãos cobertos, quanto do volume os 5 maiores vencedores levam (mediana)
WITH o AS (SELECT org, forn, count(*) n FROM v WHERE dt >= current_date - 730 GROUP BY 1,2), t AS (SELECT org, sum(n) tot, sum(n) FILTER (WHERE rk <= 5) top5 FROM (SELECT *, row_number() OVER (PARTITION BY org ORDER BY n DESC) rk FROM o) x GROUP BY org HAVING sum(n) >= 30) SELECT count(*) orgaos, round(percentile_cont(0.5) WITHIN GROUP (ORDER BY 1.0*top5/tot)::numeric,3) top5_share_mediana FROM t;
-- Q24 dos vencedores top-5 de um órgão, quantos têm >=5 vitórias ali (para mostrar desconto próprio)
WITH o AS (SELECT org, forn, count(*) n FROM v WHERE dt >= current_date - 730 GROUP BY 1,2), r AS (SELECT *, row_number() OVER (PARTITION BY org ORDER BY n DESC) rk, sum(n) OVER (PARTITION BY org) tot FROM o) SELECT count(*) top5_linhas, count(*) FILTER (WHERE n >= 5) com_5_vitorias FROM r WHERE rk <= 5 AND tot >= 30
